
version: 1.0
publish: app
services:
  app:
    image: backdrop:latest
    environment:
      BACKDROP_DB_PASSWORD: demo
      BACKDROP_DB_HOST: mysql
    ports:
    - container: 80
      public: 80

  mysql:
    image: bitnami/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: backdrop
